from .Dialog import Dialog
from .Inventario_rapido import Inventario_rapido
from .Menu_Items import Menu_Items
from .Menu_Equipo import Menu_Equipo
from .Menu_Pausa import Menu_Pausa
from .Menu import Menu
from ._opcion import _opcion
from .Ventana import Ventana
from . import modos